package cn.sz.gl.pojo;

// Generated 2017-12-5 9:37:32 by Hibernate Tools 3.4.0.CR1

/**
 * AdminUser generated by hbm2java
 */
public class AdminUser implements java.io.Serializable {

	private Integer adminId;
	private Dept dept;
	private Role role;
	private String loginname;
	private String loginpwd;
	private String realname;
	private String picpath;
	private String mobile;
	private String email;
	private String status;
	private Integer parentid;

	public AdminUser() {
	}

	public AdminUser(Integer adminId) {
		this.adminId = adminId;
	}

	public AdminUser(Integer adminId, Dept dept, Role role, String loginname,
			String loginpwd, String realname, String picpath, String mobile,
			String email, String status, Integer parentid) {
		this.adminId = adminId;
		this.dept = dept;
		this.role = role;
		this.loginname = loginname;
		this.loginpwd = loginpwd;
		this.realname = realname;
		this.picpath = picpath;
		this.mobile = mobile;
		this.email = email;
		this.status = status;
		this.parentid = parentid;
	}

	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	public Dept getDept() {
		return this.dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getLoginpwd() {
		return this.loginpwd;
	}

	public void setLoginpwd(String loginpwd) {
		this.loginpwd = loginpwd;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getPicpath() {
		return this.picpath;
	}

	public void setPicpath(String picpath) {
		this.picpath = picpath;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getParentid() {
		return this.parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

}
