package cn.sz.gl.pojo;

// Generated 2017-12-5 9:37:32 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Priviliage generated by hbm2java
 */
public class Priviliage implements java.io.Serializable {

	private Integer priid;
	private String pname;
	private String priUrl;
	private String priImage;
	private Integer parentid;
	private String status;

	public Priviliage() {
	}

	public Priviliage(Integer priid) {
		this.priid = priid;
	}

	public Priviliage(Integer priid, String pname, String priUrl, String priImage,
			Integer parentid, String status) {
		this.priid = priid;
		this.pname = pname;
		this.priUrl = priUrl;
		this.priImage = priImage;
		this.parentid = parentid;
		this.status = status;
	}

	public Integer getPriid() {
		return this.priid;
	}

	public void setPriid(Integer priid) {
		this.priid = priid;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getPriUrl() {
		return this.priUrl;
	}

	public void setPriUrl(String priUrl) {
		this.priUrl = priUrl;
	}

	public String getPriImage() {
		return this.priImage;
	}

	public void setPriImage(String priImage) {
		this.priImage = priImage;
	}

	public Integer getParentid() {
		return this.parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
