package cn.sz.gl.pojo;

// Generated 2017-12-5 9:37:32 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer roleid;
	private String roleCn;
	private String roleEn;
	private Integer parentid;
	private String status;
	private List<Priviliage> priviliages;

	public Role() {
	}

	public Role(Integer roleid) {
		this.roleid = roleid;
	}

	public Role(Integer roleid, String roleCn, String roleEn, Integer parentid,
			String status, List<Priviliage> priviliages) {
		this.roleid = roleid;
		this.roleCn = roleCn;
		this.roleEn = roleEn;
		this.parentid = parentid;
		this.status = status;
		this.priviliages = priviliages;
	}

	public Integer getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	public String getRoleCn() {
		return this.roleCn;
	}

	public void setRoleCn(String roleCn) {
		this.roleCn = roleCn;
	}

	public String getRoleEn() {
		return this.roleEn;
	}

	public void setRoleEn(String roleEn) {
		this.roleEn = roleEn;
	}

	public Integer getParentid() {
		return this.parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public List<Priviliage> getPriviliages() {
		return this.priviliages;
	}

	public void setPriviliages(List<Priviliage> priviliages) {
		this.priviliages = priviliages;
	}

}
