package cn.sz.gl.pojo;

// Generated 2017-12-5 9:37:32 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VipUser generated by hbm2java
 */
public class VipUser implements java.io.Serializable {

	private Integer userid;
	private HatArea hatArea;
	private String loginname;
	private String loginpwd;
	private String mobile;
	private String nikname;
	private String picpath;
	private String email;
	private String address;
	private String userStatus;

	public VipUser() {
	}

	public VipUser(Integer userid) {
		this.userid = userid;
	}

	public VipUser(Integer userid, HatArea hatArea, String loginname,
			String loginpwd, String mobile, String nikname, String picpath,
			String email, String address, String userStatus) {
		this.userid = userid;
		this.hatArea = hatArea;
		this.loginname = loginname;
		this.loginpwd = loginpwd;
		this.mobile = mobile;
		this.nikname = nikname;
		this.picpath = picpath;
		this.email = email;
		this.address = address;
		this.userStatus = userStatus;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public HatArea getHatArea() {
		return this.hatArea;
	}

	public void setHatArea(HatArea hatArea) {
		this.hatArea = hatArea;
	}

	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getLoginpwd() {
		return this.loginpwd;
	}

	public void setLoginpwd(String loginpwd) {
		this.loginpwd = loginpwd;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getNikname() {
		return this.nikname;
	}

	public void setNikname(String nikname) {
		this.nikname = nikname;
	}

	public String getPicpath() {
		return this.picpath;
	}

	public void setPicpath(String picpath) {
		this.picpath = picpath;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

}
